apiVersion: v1
kind: Service
metadata:
  name: minio-srv
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio-srv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-srv
  labels:
    app: minio-srv
spec:
  selector:
    matchLabels:
      app: minio-srv
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minio-srv
    spec:
      volumes:
        - name: minio-volume
          persistentVolumeClaim:
            claimName: minio-pv
      containers:
        - name: minio-srv
          image: minio/minio
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              name: minio
          volumeMounts:
            - name: minio-volume
              mountPath: "/data"
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRET_KEY
          # Readiness probe detects situations when MinIO server instance
          # is not ready to accept traffic. Kubernetes doesn't forward
          # traffic to the pod while readiness checks fail.
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
          # Liveness probe detects situations where MinIO server instance
          # is not working properly and needs restart. Kubernetes automatically
          # restarts the pods if liveness checks fail.
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20