apiVersion: v1
kind: Secret
metadata:
  name: minio-rest-api-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID:  echo -n 'YOUR-ID' | base64
  AWS_SECRET_ACCESS_KEY: echo -n 'YOUR-KEY' | base64
  AWS_REGION: echo -n 'YOUR-REGION' | base64
