spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  endpoint: http://localhost:9000
  accessKey: AKA47EXAMPLEDOC
  secretKey: JAVATESTEXAMPLEKEY

file:
  endpoint: shttp://localhost:8080
  accessKey: youAccessKey

server:
  port: 8080
